#baseURL = 'http://sebrwa.github.io/blog/'
baseURL = ""
relativeURLs = "True"
languageCode = 'en-us'
title = 'Sebastian Ochoa'
theme = 'hugo-initio-main'

[params]
    name = "Sebastian Ochoa"
    description = "About me"
    email = "ochjsj@gmail.com"
    address = "Bogota, Colombia"
    year = 2017
    avatar = "images/guy.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/bg_head.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"
    author = "Sebastian Ochoa"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownloads = false
    showClients = true

    showFooterContact = false
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

    
[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/juan-ochoa/"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/jsdj_op"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/rwarwa.rwa"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:ochoajsj@gmail.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"